=== nonesuccess243/commons/waf_demo/src/main/resources/dbgrid_config/dbgrid.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT DBGrids ((imports)?,(DBType)?,(DBGrid)*)>
<!ELEMENT imports (import)* >
<!ELEMENT import (#PCDATA) >
<!ELEMENT DBType (param?) >
<!ELEMENT param (#PCDATA) >

<!ELEMENT DBGrid (
	grid-title?,
	grid-name,
	grid-table,
	grid-cols,
	grid-label,
	grid-fields?,
	grid-relation?,
	grid-condCols?,
	grid-param?,
	grid-operation?,
	grid-where?,
	grid-queryType?,
	grid-orderBy?,
	grid-groupBy?,
	grid-test?,
	grid-color?,
	grid-rowsPerPage?,
	grid-type?,
	grid-handler?,
	grid-forwardURL?
) >




<!ELEMENT grid-title (#PCDATA) >
<!ELEMENT grid-name (#PCDATA) >
<!ELEMENT grid-table (#PCDATA) >
<!ELEMENT grid-cols (#PCDATA) >
<!ELEMENT grid-label (#PCDATA) >
<!ELEMENT grid-fields (#PCDATA) >
<!ELEMENT grid-relation (#PCDATA) >
<!ELEMENT grid-condCols (#PCDATA) >
<!ELEMENT grid-param (#PCDATA) >
<!ELEMENT grid-operation (#PCDATA) >
<!ELEMENT grid-where (#PCDATA) >
<!ELEMENT grid-queryType (#PCDATA) >
<!ELEMENT grid-orderBy (#PCDATA) >
<!ELEMENT grid-groupBy (#PCDATA) >
<!ELEMENT grid-test (#PCDATA) >
<!ELEMENT grid-color (#PCDATA) >
<!ELEMENT grid-rowsPerPage (#PCDATA) >
<!ELEMENT grid-type (#PCDATA) >
<!ELEMENT grid-handler (#PCDATA) >
<!ELEMENT grid-forwardURL (#PCDATA) >

=== nonesuccess243/commons/dbgrid/src/test/resources/dbgrid_config/woman_manage/dbgrid_batch_handle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DBGrids SYSTEM "../dbgrid.dtd" >
<DBGrids>
	<!-- 等待本辖区进行“确认接收”或者“确认迁出”的妇女列表 -->
	<DBGrid>
	<grid-title>迁移变动列表</grid-title>
		<grid-name>/woman_manage/batch_handle/approval_move/moveApprovalSearch
		</grid-name>
		<grid-table>
			 MOVE_RECORD m
			left join V_MASTER_WOMAN w on (w.id=m.WOMAN_ID)
			left join S_CODE sc on (SC.code=m.STATE)
			left join org o on (o.id=m.receive_org_id)
			left join org o1 on (o1.id=m.send_org_id)
		</grid-table>		
		<grid-cols>
			m.id mid,m.woman_id wid,w.name wname,w.id_No widNo,o1.name sendOrgName ,m.SEND_DATE ,o.name,
			m.receive_date,m.state,sc.name scname
		</grid-cols>
		<grid-label>ID$h,womanId$h,妇女姓名,妇女身份证号,迁出单位,迁出日期$d1,接收单位,接收日期$d1,状态$h,状态</grid-label>
		<grid-fields>id,womanid,womanName,wIdNo,sendOrg,sendDate,receiveOrg,receiveDate,moveState,scname</grid-fields>
		<grid-relation> ((o.inner_code like #user.employee.org.innerCode || '%'
			and (m.state	= 'RECEIVE_APPLY' )) or (o1.inner_code like #user.employee.org.innerCode || '%'
			and (m.state	= 'SEND_APPLY' )))
		</grid-relation>
		<grid-condCols>W.NAME,W.ID_NO</grid-condCols>
		<grid-param>womanName,womanIdNo</grid-param>
		<grid-operation>10,10</grid-operation>
		<grid-orderBy>m.id</grid-orderBy>
		<grid-rowsPerPage>10</grid-rowsPerPage>
	</DBGrid>
	
	<!-- 迁卡结果查询 -->
	<DBGrid>
	<grid-title>迁卡结果列表</grid-title>
		<grid-name>/woman_manage/batch_handle/approval_move/migrationCardResultQuery
		</grid-name>
		<grid-table>
			 MOVE_RECORD m left join
			V_MASTER_WOMAN w on (w.id=m.WOMAN_ID) left join
			ORG o2 ON (o2.id = w.MANAGE_UNIT_ID) LEFT JOIN
			EMPLOYEE send_e ON (send_e.id = m.SEND_EMPLOYEE_ID) LEFT JOIN
			org o1 on (o1.id=m.send_org_id) LEFT JOIN
			org o on (o.id=m.receive_org_id) LEFT JOIN
			EMPLOYEE receive_e ON (receive_e.id = m.RECEIVE_EMPLOYEE_ID) LEFT JOIN
			S_CODE sc on (SC.code=m.STATE)
		</grid-table>		
		<grid-cols>
		    m.id id,w.id womanid,w.name wname, w.id_No widNo,o1.name sendOrg,m.SEND_DATE sendDate,send_e.name sendEY,o.name receiveOrg,
			m.RECEIVE_DATE receiveDate,receive_e.name receiveEY,sc.name scname
		</grid-cols>
		<grid-label>ID$h,womanId$h,妇女姓名,妇女身份证号,迁出单位,迁出日期$d1,迁出操作人,接收单位,接收日期$d1,迁入操作人,状态</grid-label>
		<grid-fields>id,womanid,wname,wIdNo,sendOrg,sendDate,sendEY,receiveOrg,receiveDate,receiveEY,scname</grid-fields>
		<grid-relation> 
			 ((o.inner_code like #user.employee.org.innerCode || '%'
			and (m.state = 'SEND_APPLY' )) or (o1.inner_code like #user.employee.org.innerCode || '%'
			and (m.state = 'RECEIVE_APPLY' )))
		</grid-relation>
		<grid-condCols>W.NAME,W.ID_NO</grid-condCols>
		<grid-param>womanName,womanIdNo</grid-param>
		<grid-operation>10,10</grid-operation>
		<grid-orderBy>m.id</grid-orderBy>
		<grid-rowsPerPage>10</grid-rowsPerPage>
	</DBGrid>
	
	<!-- 历史查询 -->
	<DBGrid>
	<grid-title>历史迁卡列表</grid-title>
		<grid-name>/woman_manage/batch_handle/approval_move/migrationCardHistoryQuery
		</grid-name>
		<grid-table>
			MOVE_RECORD m left join
			V_MASTER_WOMAN w on (w.id=m.WOMAN_ID) left join
			ORG o2 ON (o2.id = w.MANAGE_UNIT_ID) LEFT JOIN
			EMPLOYEE send_e ON (send_e.id = m.SEND_EMPLOYEE_ID) LEFT JOIN
			org o1 on (o1.id=m.send_org_id) LEFT JOIN
			org o on (o.id=m.receive_org_id) LEFT JOIN
			EMPLOYEE receive_e ON (receive_e.id = m.RECEIVE_EMPLOYEE_ID) LEFT JOIN
			S_CODE sc on (SC.code=m.STATE)
		</grid-table>		
		<grid-cols>
		    m.id id,w.id womanid,w.name wname, w.id_No widNo,o1.name sendOrg,m.SEND_DATE sendDate,send_e.name sendEY,o.name receiveOrg,
			m.RECEIVE_DATE receiveDate,receive_e.name receiveEY,sc.name scname
		</grid-cols>
		<grid-label>ID$h,womanId$h,妇女姓名,妇女身份证号,迁出单位,迁出日期$d1,迁出操作人,接收单位,接收日期$d1,迁入操作人,状态</grid-label>
		<grid-fields>id,womanid,wname,wIdNo,sendOrg,sendDate,sendEY,receiveOrg,receiveDate,receiveEY,scname</grid-fields>
		<grid-relation> 
			o2.inner_code LIKE #user.employee.org.innerCode || '%' AND (m.STATE != 'SEND_APPLY' OR m.STATE != 'RECEIVE_APPLY')
		</grid-relation>
		<grid-condCols>W.NAME,W.ID_NO</grid-condCols>
		<grid-param>womanName,womanIdNo</grid-param>
		<grid-operation>10,10</grid-operation>
		<grid-orderBy>m.id DESC</grid-orderBy>
		<grid-rowsPerPage>10</grid-rowsPerPage>
	</DBGrid>
	<!-- 等待本辖区进行“确认接收”的妇女列表 -->
	<!-- 显示转卡记录表中，状态为转出等待接收，接收单位为本辖区的记录 -->
	<DBGrid>
	<grid-title>迁入请求列表</grid-title>
		<grid-name>/woman_manage/batch_handle/approval_receive/moveReceiveApprovalSearch
		</grid-name>
		<grid-table>
			 MOVE_RECORD m
			left join V_COMMON_WOMAN w on (w.id=m.WOMAN_ID)
			left join S_CODE sc on (SC.code=m.STATE)
			left join org o on (o.id=m.receive_org_id)
		</grid-table>		
		<grid-cols>
			m.id mid,w.name wname,w.id_No widNo,o.name oname,m.SEND_DATE mdate
		</grid-cols>
		<grid-label>ID$h,妇女姓名,妇女身份证号,原管理单位,原管理单位转卡日期$d1</grid-label>
		<grid-fields>id,womanName,wIdNo,sendRemark,sendDate</grid-fields>
		<grid-relation> o.inner_code like #user.employee.org.innerCode || '%'
			and m.state	= 'RECEIVE_APPLY'
		</grid-relation>
		<grid-condCols>W.NAME,W.ID_NO</grid-condCols>
		<grid-param>womanName,womanIdNo</grid-param>
		<grid-operation>10,10</grid-operation>
		<grid-orderBy>m.id</grid-orderBy>
		<grid-rowsPerPage>10</grid-rowsPerPage>
	</DBGrid>
	<!-- 等待本辖区进行确认迁出的妇女列表-->
	<DBGrid>
	<grid-title>迁出请求列表</grid-title>
		<grid-name>/woman_manage/batch_handle/approval_send/moveSendApprovalSearch</grid-name>
		<grid-table>
			move_record m
			left join V_COMMON_WOMAN w on (w.id=m.WOMAN_ID)
			left join org o on (o.id=m.RECEIVE_ORG_ID)
			left join org wo on ( wo.id=w.manage_unit_id)
		</grid-table>
		
		<grid-cols>
			m.id mid,w.name wname,w.id_No widno,o.name oname,m.RECEIVE_DATE mdate
		</grid-cols>
		<grid-label>ID$h,妇女姓名,妇女身份证号,新管理单位,请求日期$d1,</grid-label>
		<grid-fields>id,womanName,widNo,orgName,date</grid-fields>
		<grid-relation>  m.state = 'SEND_APPLY' and wo.inner_code like #user.employee.org.innerCode || '%'
		</grid-relation>
		<grid-condCols>W.NAME,W.ID_NO</grid-condCols>
		<grid-param>womanName,womanIdNo</grid-param>
		<grid-operation>10,10</grid-operation>
		<grid-orderBy>m.id</grid-orderBy>
		<grid-rowsPerPage>10</grid-rowsPerPage>
	</DBGrid>
	<!-- 用于显示批量退出育龄期二级菜单提示的dbgrid-->
	<DBGrid>
	
		<grid-name>/woman_manage/batch_handle/childbearing_age/OutOfChildbearingAgeBatch</grid-name>		
		<grid-table>
				v_woman_nocomplete_transaction w
				left join org o on (o.id=w.MANAGE_UNIT_ID)
		</grid-table>
		<grid-cols>
			<!-- 			"ADD_MONTHS"(w.BIRTHDAY,600)表示在生日上加上600个月，也就是49年 就等于应该退出日期-->
				w.id WID,o.name oname,w.name wname,w.id_no widno,w.birthday birthday,
				"ADD_MONTHS"(w.BIRTHDAY,600) outdate
		</grid-cols>
		
		<grid-label>ID$h,管理单位,妇女姓名,妇女身份证号,妇女出生日期$d1,应退出日期$d1</grid-label>
		<grid-fields>id,oname,name,idNo,birthday,outdate</grid-fields>
		<grid-relation>w.MANAGEMENT_STATE = 'NORMAL' and  "ADD_MONTHS"(w.BIRTHDAY,600) &lt;= SYSDATE and o.INNER_CODE like #user.employee.org.innerCode || '%'
		</grid-relation>		
		<grid-orderBy>w.birthday,w.id</grid-orderBy>
		<grid-rowsPerPage>20</grid-rowsPerPage>
	</DBGrid>
	<!-- 用于批量退出育龄期页面的查询功能-->
	<DBGrid>
	<grid-title>批量退出育龄期列表</grid-title>
		<grid-name>/woman_manage/batch_handle/childbearing_age/OutOfChildbearingAgeBatchSearch</grid-name>		
		<grid-table>
				v_woman_nocomplete_transaction w
				left join org o on (o.id=w.MANAGE_UNIT_ID)
		</grid-table>
		<grid-cols>
			<!-- 			"ADD_MONTHS"(w.BIRTHDAY,600)表示在生日上加上600个月，也就是49年 就等于应该退出日期-->
				w.id WID,o.name oname,w.LIVING_NOW_ADDRESS livingName,w.name wname,'',w.id_no widno,w.birthday birthday,
				"ADD_MONTHS"(w.BIRTHDAY,600) outdate
		</grid-cols>
		
		<grid-label>ID$h,管理单位,现居住地址,妇女姓名,操作,妇女身份证号,妇女出生日期$d1,应退出日期$d1</grid-label>
		<grid-fields>id,oname,livingName,name,oper,idNo,birthday,outdate</grid-fields>
		<grid-relation>w.MANAGEMENT_STATE = 'NORMAL'  and o.INNER_CODE like #user.employee.org.innerCode || '%'
		</grid-relation>				
		<grid-condCols>w.name,w.id_No,"ADD_MONTHS"(w.BIRTHDAY^600)$d,"ADD_MONTHS"(w.BIRTHDAY^600)$d</grid-condCols>
		<grid-param>womanName,womanIdNo,startDate,endDate</grid-param>	
		<grid-operation>10,10,4,6</grid-operation>
		<grid-orderBy>w.birthday,w.id</grid-orderBy>
		<grid-rowsPerPage>10</grid-rowsPerPage>
	</DBGrid>
</DBGrids>

=== nonesuccess243/commons/waf_demo/src/main/resources/dbgrid_config/dbgrids.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DBGrids SYSTEM "dbgrid.dtd" >

<DBGrids>
	<DBType>
		<param>MYSQL</param>
	</DBType>
	<!-- </>sender_id,send_date,is_system, ,content,remark,state -->
	<!-- 查询消息 -->
	<DBGrid>
		<grid-name>/public/demo/dbgrid</grid-name>
		<grid-table>
			S_MODULE_ITEM
		</grid-table>
		<grid-cols>
			ID, CODE, NAME, URL
		</grid-cols>
		<grid-label>
			id$h, code, name, url
		</grid-label>
		<grid-fields>
			id, code, name, url
		</grid-fields>
		<grid-relation>

		</grid-relation>
		<grid-orderBy>
			id
		</grid-orderBy>
		<grid-groupBy></grid-groupBy>
		<grid-rowsPerPage>20</grid-rowsPerPage>
	</DBGrid>
	<DBGrid>
		<grid-title>
			传感器类型
		</grid-title>
		<grid-name>/equipment/getsensor</grid-name>
		<grid-table>
			SENSOR
		</grid-table>
		<grid-cols>
			ID, NO, FRONT_TERMINAL_I_D, POSITION, MONITOR_RANGE
		</grid-cols>
		<grid-label>
			编号, 编号, 前端机, 地理位置 , 监控范围
		</grid-label>
		<grid-fields>
			id, no, frontTerminalID, position ,monitorRange
		</grid-fields>
		<grid-relation>

		</grid-relation>
		<grid-orderBy>
			id
		</grid-orderBy>
		<grid-groupBy></grid-groupBy>
		<grid-rowsPerPage>20</grid-rowsPerPage>
	</DBGrid>
</DBGrids>

=== nonesuccess243/commons/wafdemo/src/main/resources/dbgrid_config/dbgrids.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DBGrids SYSTEM "dbgrid.dtd" >

<DBGrids>
	
	<!-- YWAF相关 -->
	<DBType>
		<param>MYSQL</param>
	</DBType>
	<!-- </>sender_id,send_date,is_system, ,content,remark,state -->
	<!-- 查询消息 -->
       <DBGrid>
       	<grid-name>/public/demodbgrid/demo</grid-name>
			<grid-table>
			    DEMO_MODEL
			</grid-table>
			<grid-cols>
				ID, NAME, COUNT, CURRENT_DATE, CURRENT_TIME
			</grid-cols>
			<grid-label>
			   	id, 名称,数量,当前日期$d,当前时间$t
			</grid-label>
			<grid-fields>
			   	id, name, count, current_date, current_time
			</grid-fields>
			<grid-orderBy>
			    id
			</grid-orderBy>
			<grid-rowsPerPage>20</grid-rowsPerPage>
       </DBGrid>
</DBGrids>

=== nonesuccess243/commons/dbgrid/src/test/resources/dbgrid_config/dbgrids.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DBGrids SYSTEM "dbgrid.dtd" >

<DBGrids>
	<imports>
		<!-- 育子系统 -->
		<import>dbgrid_config/woman_manage/dbgrid_batch_handle.xml</import>
	</imports>
	
	<!-- YWAF相关 -->
	<DBType>
		<param>ORACLE</param>
	</DBType>
	<!-- </>sender_id,send_date,is_system, ,content,remark,state -->
	<!-- 查询消息 -->
       <DBGrid>
       	<grid-name>/public/message/displaymessageuser</grid-name>
			<grid-table>
			    <!-- message meg,message_ower megor,s_code sde,s_user us -->
			    message_ower megor LEFT JOIN
				message meg ON (megor.message_id = meg.id) LEFT JOIN
				s_code sde ON (sde.code = megor.receive_state)
			</grid-table>
			<grid-cols>
				megor.message_id,meg.title,meg.send_date,sde.name
			</grid-cols>
			<grid-label>
			    megor.message_id$h,标题,时间$d1,状态
			</grid-label>
			<grid-fields>
			    id,title,receive_date,name
			</grid-fields>
			<grid-relation>
			    megor.receiver_id = #employee.id
			</grid-relation>
			<grid-orderBy>
			    CASE megor.receive_state WHEN 'UNREAD' THEN 'READ' END,meg.send_date desc
			</grid-orderBy>
			<grid-rowsPerPage>20</grid-rowsPerPage>
       </DBGrid>
       <!-- 行政区划查询 -->
       <DBGrid>
		<grid-title>行政区划查询</grid-title>
		<grid-name>/public/orgNameQuery/orgNameQuery</grid-name>
		<grid-table>
		   	ORG o1 LEFT JOIN
    		ORG o2 ON (o2.INNER_CODE = o1.PARENT_CODE)
		</grid-table>
		<grid-cols>
		    o1.ID oId,
		    o1.NAME oname,
		    o2.NAME sname
		</grid-cols>
		<grid-label>ID$h,单位名称,上级管理单位
		</grid-label>
		<grid-fields>oId,oname,sname
		</grid-fields>
		<grid-relation>
			o1.INNER_CODE LIKE '12%' 
			and (o1.name like '%' || @param || '%' or o1.spell_first like '%' || @param || '%' or o1.spell_all like '%' || @param || '%')
		</grid-relation>
		<grid-rowsPerPage>15</grid-rowsPerPage>
	</DBGrid>
</DBGrids>

=== nonesuccess243/commons/waf_demo/src/main/resources/dbgrid_config/equipment/sensor/getsensor.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DBGrids SYSTEM "dbgrid.dtd" >

<DBGrids>
	<DBType>
		<param>MYSQL</param>
	</DBType>
	<!-- </>sender_id,send_date,is_system, ,content,remark,state -->
	<!-- 查询消息 -->
       <DBGrid>
       	<grid-name>/equipment/getsensor</grid-name>
			<grid-table>
			    E_SENSOR
			</grid-table>
			<grid-cols>
				ID, NO, FRONT_TERMINAL_I_D, POSITION
			</grid-cols>
			<grid-label>
			    id$h, no, frontTerminalID, position
			</grid-label>
			<grid-fields>
			    id, no, frontTerminalID, position
			</grid-fields>
			<grid-relation>
			    
			</grid-relation>
			<grid-orderBy>
			    id
			</grid-orderBy>
			<grid-groupBy></grid-groupBy>
			<grid-rowsPerPage>20</grid-rowsPerPage>
       </DBGrid>
</DBGrids>
